import Config from './config.js';

class FolderDiscoveryService {
    constructor() {
        this.excludedFolders = new Set([
            '.git', '.github', '.vscode', 'node_modules',
            'js', 'css', 'view', 'assets', 'dist', 'build'
        ]);
        this.excludedFiles = new Set([
            'README.md', 'README-NEW.md', 'LICENSE.md', 'CHANGELOG.md',
            'microservices.md', 'quiestions.md', 'soft-skills.md'
        ]);
    }

    /**
     * Discover all topic folders and their markdown files
     * Uses the structure.json file generated by the build script
     */
    async discoverFolders() {
        try {
            // Try to load from pre-generated structure file
            const response = await fetch(`${Config.basePath}/structure.json`);
            if (response.ok) {
                return await response.json();
            }
        } catch (error) {
            console.log('structure.json not found, using fallback');
        }

        // Fallback to hardcoded structure
        return this.getFallbackStructure();
    }

    getFallbackStructure() {
        return {
            'agile': ['questions.md'],
            'algorithms': ['coding-problems.md', 'complexity.md', 'questions.md', 'recursion.md', 'sorting.md'],
            'api': ['concepts.md', 'graphql.md', 'kafka.md', 'rest.md', 'soap.md', 'streaming.md'],
            'ballerina': ['questions.md'],
            'cloud': ['concepts.md', 'docker.md', 'kubernetes.md'],
            'concurrency': ['concepts.md'],
            'cryptography': ['concepts.md', 'rsa.md'],
            'data-structures': ['array.md', 'heap.md', 'stack.md'],
            'database': ['acid.md', 'concepts.md', 'indexing.md', 'normalization.md', 'nosql.md', 'scenario.md', 'sql.md'],
            'design-patterns': ['basics.md'],
            'devops': ['concepts.md', 'ci-cd.md', 'monitoring.md'],
            'git': ['basics.md', 'commands.md', 'advanced.md'],
            'hr': ['questions.md'],
            'java': ['java-collections-advanced.md', 'java-collections.md', 'java-data-types.md', 'java-exceptions.md', 'java-keywords.md', 'java-oop.md', 'java-strings.md', 'java-threading.md'],
            'javascript': ['questions.md'],
            'linux': ['questions.md'],
            'microservices': ['microservices.md'],
            'ml': ['concepts.md'],
            'networking': ['http.md', 'osi.md', 'ssh.md', 'ssl.md', 'tcp.md'],
            'node': ['questions.md'],
            'oop': ['abstraction.md', 'basics.md', 'encapsulation.md', 'inheritance.md', 'polymorphism.md'],
            'python': ['questions.md', 'advanced.md'],
            'questions': ['questions.md'],
            'react': ['react.md', 'hooks.md', 'state-management.md'],
            'security': ['concepts.md', 'owasp.md'],
            'spring': ['questions.md'],
            'system-design': ['concepts.md', 'patterns.md'],
            'testing': ['questions.md']
        };
    }

    isValidFolder(name) {
        return !this.excludedFolders.has(name) && !name.startsWith('.');
    }

    isValidFile(name) {
        return name.endsWith('.md') && !this.excludedFiles.has(name);
    }
}

const folderDiscovery = new FolderDiscoveryService();
export default folderDiscovery;
